export default function SiteFooter() {
  return (
    <footer className="mt-12 border-t border-[#dde3ec] bg-white">
      <div className="mx-auto max-w-6xl px-6 py-6 text-sm text-[#5a6b82]">
        <p>
          © {new Date().getFullYear()} Royal Cyber · commercetools Insights.
          Generated by the commercetools Department Agent &amp; Quarterly Plan
          Agent.
        </p>
        <p className="mt-1 text-xs text-[#8a97aa]">
          Content reflects the most recent agent run. Update the data files to
          refresh.
        </p>
      </div>
    </footer>
  );
}
